{% set name = "maturin" %}
{% set version = "0.7.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13403587b64eb9571fc8886608fac6a301b791d0670ef2fb79e60add39ac8aec

build:
  number: 0
  skip: true  # [py27]
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - rust
  host:
    - pip
    - python
  run:
    - python

test:
  commands:
    - maturin --help

about:
  home: https://github.com/PyO3/maturin
  license: MIT
  license_family: MIT
  license_file: license-mit
  summary: >-
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages

extra:
  recipe-maintainers:
    - apcamargo
