{% set name = "maturin" %}
{% set version = "0.12.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 222e5e53011cc999c06fc7d854df7cc77ee3f7391a749a4edcc5ab4c1b9c2c98

build:
  number: 0
  skip: true  # [py27]
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    # seems to work with defaults from conda-forge-pinning (at the moment)
    - rust  # [not osx]
    # investigating...
    - rust >=1.54  # [osx]
  host:
    - pip
    - python
    - toml
  run:
    - python
    - toml >=0.10.2,<0.11

test:
  commands:
    - maturin --help

about:
  home: https://github.com/PyO3/maturin
  license: MIT
  license_family: MIT
  license_file: license-mit
  summary: >-
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages

extra:
  recipe-maintainers:
    - apcamargo
